// error Reducer
export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
// auth Reducer
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const ALL_USERS_LOADED = "ALL_USERS_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const UPDATE_PROFILE = "UPDATE_PROFILE";
export const UPDATE_ERROR = "UPDATE_TICKET";
export const UPDATE_SUCCESS = "UPDATE_SUCCESS";
// ticket Reducer
export const LOAD_TICKETS = "LOAD_TICKETS";
export const LOAD_TICKET_ERROR = "LOAD_TICKET_ERROR";
export const LOAD_USER_TICKETS = "LOAD_USER_TICKETS";
export const POST_TICKET = "POST_TICKET";
export const UPDATE_TICKET = "UPDATE_TICKET";
export const DELETE_TICKET = "DELETE_TICKET";
export const CLEAR_TICKETS = "CLEAR_TICKETS";
export const POST_ERROR = "POST_ERROR";
export const POST_SUCCESS = "POST_SUCCESS";
export const CURRENT_TICKET = "CURRENT_TICKET";
export const POST_COMMENT = "POST_COMMENT";
export const IS_NEW_COMMENT = "IS_NEW_COMMENT";
export const COMMENT_ERROR = "COMMENT_ERROR";
export const POST_IMAGE = "POST_IMAGE";
export const IMAGE_ERROR = "IMAGE_ERROR";
export const UPDATE_PROFILE_IMAGE = "UPDATE_PROFILE-IMAGE";
export const UPDATE_PROFILE_IMAGE_ERROR = "UPDATE_PROFILE_IMAGE_ERROR";
export const IS_LOADING = "IS_LOADING";
export const POST_SINGLE_IMAGE = "POST_SINGLE_IMAGE";
export const CLEAR_SINGLE_IMAGE = "CLEAR_SINGLE_IMAGE";
export const PROFILE_IMAGE_LOADING = "PROFILE_IMAGE_LOADING";
export const DELETE_PROFILE_IMAGE = "DELETE_PROFILE_IMAGE"
export const DELETE_NEW_TIX_IMAGE = "DELETE_NEW_TIX_IMAGE"
// message Reducer
export const LOAD_MESSAGES = "LOAD_MESSAGES"
export const POST_MESSAGES = "POST_MESSAGES"
export const MESSAGE_ERROR = "MESSAGE_ERROR"
export const POST_MESSAGE_SUCCESS = "POST_MESSAGE_SUCCESS"
export const UPDATE_MESSAGE = "UPDATE_MESSAGE"

